### ISSUE TITLE
 a Duplicate definition about the fmincon?

### ISSUE THREAD

**Issue by AdamPengG** [Hangcil/fmincon-with-Cpp#3]
Hi Hangcil, I have update your newest lib on today. Then I tried the ub & lb options.But when catkin_make, the terminal showing ```
"sci_arma::fmincon(std::function<double (arma::Col<double>&)> const&, arma::Col<double>&, arma::Mat<double>&, arma::Mat<double>&, arma::Mat<double>&, arma::Mat<double>&, arma::Col<double>&, arma::Col<double>&, options const&)'
collect2: error: ld returned 1 exit status"
```
Is there a Duplicate definition about the fmincon?

**Comment by AdamPengG** [comment]
Addd this static x_fval fmincon(const obj_fun& f, vec& x0, vec& lb, vec& ub,const nonl_con& c); in sci_aram.h is OK

**Comment by Hangcil** [comment]
Thanks for your feedback. I've checked my code and found some errors in Cmakelists.txt. But, so far, I have not spotted a duplication of the function. The definition of the function ```static x_fval fmincon(const obj_fun& f, vec& x0, vec& lb, vec& ub,const nonl_con& c)``` has not been created yet in this project. I'll complete it soon.
