### ISSUE TITLE
Nonlinear Equality Constraint is missed

### ISSUE THREAD

**Issue by Elektron97** [Hangcil/fmincon-with-Cpp#5]
I can't found the implementation of nonlinear equality constraint, it is implemented or will be implemented?

**Comment by Hangcil** [comment]
Actually it has been implemented as the example demonstrated, but the function fmincon() focus more on linear constraints. 
Moreover, The algorithms used here for constraint problems are so-called "direct search" methods which require neither of the differenciblities of the constraints or functions. I wish to rewrite the library, add more commonly applied methods and bring up a new interface for multiple constraint problems. I'm working on this at https://github.com/Hangcil/some-solvers-for-numerical-optimization. There may be quite a lot issues, but I think I can finalize it this summer.

**Comment by Elektron97** [comment]
Hi @Hangcil, thank you for your answer. I can't find how you can specify a nonlinear **equality** constraint. Maybe I'm wrong but in the examples there is only a nonlinear **inequality** constraint.

```c++
// define non-linear inequality constraints c(x)<=0
auto c = [](vec &x) -> vec
{
vec temp = {25 * x(0) * x(0) + x(1) * x(1) + x(2) * x(2) + x(3) * x(3) - 50 * x(3)};
return temp;
};
```
After a rapid check on your src code, I still cannot found I can specify a nonlinear equality constraint.

**Comment by Hangcil** [comment]
That's right. Thank you for the advice. The nonlinear equality constraints are not implemented yet. Currently you can set nonlinear equality c(x)=0 as "c(x)<=0, -c(x)<=0". This may be some sort of awkward, but I will try my effort to rewrite the library, especially for the logic of the input parameters and more efficient and convenient algorithms.

**Comment by Elektron97** [comment]
Don't worry, you made an excellent work. I will follow every update, reimplementing your stuff in a ROS pkg, as you can see in my [fork](https://github.com/Elektron97/fmincon-ROScpp). Thank you for the suggestion to use these constraints.

$$
\begin{cases}
c(x) \leq 0 \\
c(x) \geq 0
\end{cases} \rightarrow c(x) = 0
$$
